### ISSUE TITLE
error/import.c/ImportImageCommand/1302 Error

### ISSUE THREAD

**Issue by hiromaily** [thelinuxlich/prisma-mysql-comments-generator#1] opened 2024-10-31 03:17 UTC
I tried to use it for MySQL8.0 Database.

However I got errors.

```
Error: Generator "prisma-mysql-comments-generator" failed:

import: delegate library support not built-in '' (X11) @ error/import.c/ImportImageCommand/1302.
import: delegate library support not built-in '' (X11) @ error/import.c/ImportImageCommand/1302.
import: delegate library support not built-in '' (X11) @ error/import.c/ImportImageCommand/1302.
import: delegate library support not built-in '' (X11) @ error/import.c/ImportImageCommand/1302.
import: delegate library support not built-in '' (X11) @ error/import.c/ImportImageCommand/1302.
import: delegate library support not built-in '' (X11) @ error/import.c/ImportImageCommand/1302.
import: delegate library support not built-in '' (X11) @ error/import.c/ImportImageCommand/1302.
import: delegate library support not built-in '' (X11) @ error/import.c/ImportImageCommand/1302.
/Users/me/orgs/project/node_modules/.bin/prisma-mysql-comments-generator: line 9: syntax error near unexpected token `('
/Users/me/orgs/project/node_modules/.bin/prisma-mysql-comments-generator: line 9: `const run = (fn) => fn();'
````

### environment

- prisma: 5.19.0
- Node: v22.8.0

**Comment by thelinuxlich** [comment] 2024-11-13 12:45
that's super weird, it's like the Node runtime doesn't know how to use arrow functions. Are you sure the runtime is `22.8.0`?

**Comment by thelinuxlich** [comment] 2024-11-24 21:24
Closing because it's lacking reproducibility.

**Closed as completed by thelinuxlich** 2024-11-24 21:24 UTC
